animated set
adrianpricop/AnimatedSet pull request #1
Opened 2018-07-12 09:41 UTC by adrianpricop

2018-07-12 11:17 UTC, emil622 requested changes

2018-07-12 11:17 UTC, emil622 commented on test/CardRender.swift
> +class cardRender
Classes must have capitalised naming, rename to "CardRender"

2018-07-12 11:17 UTC, emil622 commented on test/CardRender.swift
> +    {
I recommend adding opening braces on the same line with the block/method body. We have this convention on all other projects.

2018-07-12 11:17 UTC, emil622 commented on test/CardRender.swift
> +    public func getColor(for card: Card) -> UIColor
Separate methods with an empty line

2018-07-12 11:17 UTC, emil622 commented on test/ContainerView.swift
> +class ContainerView: UIView{
Add an empty space before {

2018-07-12 11:17 UTC, emil622 commented on test/ContainerView.swift
> +                }else if inPlayCards.count < buttons.count
Add an empty space before 'else'

2018-07-12 11:17 UTC, emil622 commented on test/ContainerView.swift
> +
Remove these empty lines

2018-07-12 11:17 UTC, emil622 commented on test/ContainerView.swift
> +            return CGRect(x: bounds.size.width * 0.025, y: bounds.size.height * 0.025, width: bounds.size.width * 0.95, height: bounds.size.height * 0.95)
split CGRect constructor on multiple lines for better readability

2018-07-12 11:17 UTC, emil622 commented on test/ContainerView.swift
> +//    func shuffle()
Remove commented code

2018-07-12 11:17 UTC, emil622 commented on test/SetGame.swift
> +//            if selectedCards.count == 3
Remove commented code

2018-07-13 08:39 UTC, BogdanPintilei requested changes

2018-07-13 08:39 UTC, BogdanPintilei commented on test/ButtonExtension.swift
> +{
As a general convention when creating a new class, extension, struct etc. you shoud move the bracket on the declaration line with an empty space between and a empty line after

2018-07-13 08:39 UTC, BogdanPintilei commented on test/ButtonExtension.swift
> +}
Also as a general convention you should a single  empty line before the last bracket.

2018-07-13 08:39 UTC, BogdanPintilei commented on test/Card.swift
> +
Only one single line

2018-07-13 08:39 UTC, BogdanPintilei commented on test/Card.swift
> +//    static var identifierFactori = 0
delete unused commented out code

2018-07-13 08:39 UTC, BogdanPintilei commented on test/ContainerView.swift
> +    func DidFinishAnimating() {
begin functions with a small letter

2018-07-13 08:39 UTC, BogdanPintilei commented on test/ContainerView.swift
> +    var buttonDeckFrame = CGRect()
Group all the variables at the begining of the class.

2018-07-13 08:39 UTC, BogdanPintilei commented on test/IntExtension.swift
> +{
Refactor brackets.

2018-07-13 08:39 UTC, BogdanPintilei commented on test/SetGame.swift
> +    var isSetCards = [Int:Card]()
Delete empty spaces between variable declarations

2018-07-13 08:39 UTC, BogdanPintilei commented on test/SetGame.swift
> +                    {
IF you have time you could replace the for in for logic, and use something like the mapping with the map function

2018-07-13 08:39 UTC, BogdanPintilei commented on test/SetGame.swift
> +                        let card = Card(matching: false, isSelected: false, identifier: identifier, cardColor: color, cardSimbol: simbol, cardNumber: number, cardShading: shading)
separeate the attributes from the Card initialization on single lines

2018-07-13 08:39 UTC, BogdanPintilei commented on test/ViewController.swift
> +        game.cardGenerator()
create a multiple methods for all commands in the viewDidLoad and call them in viewDidLoad

2018-07-13 08:39 UTC, BogdanPintilei commented on test/ViewController.swift
> +                                                height: drawThreeCardsButton.frame.height)
The same as in viewDidLoad

2018-07-13 08:39 UTC, BogdanPintilei commented on test/ViewController.swift
> +    @IBOutlet weak var cardsContainerView: ContainerView!
Delete empty lines between outlets

2018-07-13 08:39 UTC, BogdanPintilei commented on test/ViewController.swift
> +}
Refactor the class with all the conventios proposed until now

2018-07-17 07:28 UTC, merged